services:
  web:
    image: nginx
    ports:
      - "8080:8080"
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ./src:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
